apiVersion: apps/v1
kind: Deployment
metadata:
  name: court-herald
  labels:
    app: court-herald
spec:
  selector:
    matchLabels:
      app: court-herald
  replicas: 3
  template:
    metadata:
      labels:
        app: court-herald
    spec:
      containers:
        - name: court-herald
          image: robherley/court-herald:0.0.1
          imagePullPolicy: 'Always'
          env:
            - name: BACKEND_URL
              value: 'plague-doctor-svc.default.svc.cluster.local:5000/api/v1/plague_doctor'
            - name: MONGO_URI
              value: 'mongodb://mongo-0.mongo:27017'
            - name: JWT_SECRET
              value: 'tyr-dev'
            - name: JWT_REALM
              value: 'tyr-dev'
            - name: JOB_SECRET
              value: 'tyr-dev'
            - name: BRIAN_VERSION
              value: '0.1.0'
---
apiVersion: v1
kind: Service
metadata:
  name: court-herald-svc
spec:
  selector:
    app: court-herald
  type: NodePort
  ports:
    - port: 4444
      nodePort: 32223
