apiVersion: apps/v1
kind: Deployment
metadata:
  name: court-herald
  labels:
    app: court-herald
spec:
  selector:
    matchLabels:
      app: court-herald
  replicas: 1
  template:
    metadata:
      labels:
        app: court-herald
    spec:
      serviceAccountName: job-bot
      containers:
        - name: court-herald
          image: robherley/court-herald:e94b4df
          imagePullPolicy: 'Always'
          env:
            - name: ENV
              value: 'production'
            - name: MONGO_URI
              value: 'mongo-0.mongo:27017'
            - name: BACKEND_URL
              value: 'http://plague-doctor-svc.default.svc.cluster.local:5555/api/v1/plague_doctor'
            - name: JWT_SECRET
              value: 'tyr-dev'
            - name: JWT_REALM
              value: 'tyr-dev'
            - name: JOB_SECRET
              value: 'tyr-dev'
            - name: BRIAN_VERSION
              value: 'debug-1'
---
apiVersion: v1
kind: Service
metadata:
  name: court-herald-svc
spec:
  selector:
    app: court-herald
  type: NodePort
  ports:
    - port: 4444
      nodePort: 32223
